name: Production Deploy
run-name: ${{ github.actor }} prod deploy ðŸš€
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate New Secret and Update application.conf
        shell: bash
        run: |
          # Generate a new secret
          CRYPTO_SECRET=$(uuidgen)
          HTTP_SECRET=$(uuidgen)
          echo "Generated secret for deployment: $CRYPTO_SECRET and $HTTP_SECRET"

          # Update application.conf in place.
          sed -i.bak "s/\(play\.crypto\.secret *= *\"\)changeme\(\".*\)/\1${CRYPTO_SECRET}\2/" airline-web/conf/application.conf
          sed -i.bak "s/\(play\.http\.secret\.key *= *\"\)changeme\(\".*\)/\1${HTTP_SECRET}\2/" airline-web/conf/application.conf

          grep 'play.crypto.secret' airline-web/conf/application.conf

      - name: SCP to Contabo
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.production_host }}
          username: ${{ secrets.production_user }}
          key: ${{ secrets.production_key }}
          port: 22
          script_stop: true
          source: "."
          strip_components: 0
          target: "/var/www/myfly.club/airline/"
      - name: Build java, restart server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.production_host }}
          username: ${{ secrets.production_user }}
          key: ${{ secrets.production_key }}
          port: 22
          script_stop: true
          script: |
            cd /var/www/myfly.club/airline/airline-data/
            sbt clean publishLocal
      